### ISSUE TITLE
Won't Install on ⁨2.1.62

### ISSUE THREAD

**Issue by DoctorToBeIn23** [AnKingMed/Browser-Resizer#11]
Version ⁨2.1.62 (bf05fae9)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
MacBook Pro
13-inch, M1, 2020
macOS Ventura Version 13.2.1

Invalid code, or add-on not available for your version of Anki.

**Comment by aPaci95** [comment]
Is there any fix?

**Comment by AnKingMed** [comment]
A lot changed and I haven't looked into fixing this. It needs a pretty reasonable overhaul (or new addon potentially..). What features of this are you hoping for?

**Comment by aPaci95** [comment]
I would like to have an UI in which i can see more at once.. i have a 2k screen so It"s not a problem to have everything smaller and every element closer to the other. Browser resizer was perfect, because i prefer to have something more pratical instead of something brautiful. I don't Need amy particular feature, Just an UI in which there are less empty spaces

**Comment by aPaci95** [comment]
I would like to have an UI in which i can see more at once.. i have a 2k screen so It"s not a problem to have everything smaller and every element closer to the other. Browser resizer was perfect, because i prefer to have something more pratical instead of something brautiful. I don't Need amy particular feature, Just an UI in which there are less White spaces

**Comment by AnKingMed** [comment]
Sounds reasonable to me. Could look into it. @abdnh do you have any time?  We may need to create a second branch of this and exclude some parts of the add-on if needed

Seems reasonable to resize the space between lines in the Anki sidebar and browser though as those are handy features

**Comment by abdnh** [comment]
Will have a look next week.

**Comment by abdnh** [comment]
I've merged changes from #4 and #7 to the main branch and made changes to make most things work for Anki 2.1.50+. I vote to remove the image shrinking options, as we now have a built-in image resizer.

Here's an update for you to test @DoctorToBeIn23 @AnKingMed @aPaci95 
[Browser-Resizer.zip](https://github.com/AnKing-VIP/Browser-Resizer/files/13246008/Browser-Resizer.zip)

**Comment by aPaci95** [comment]
Such a wonderful news! Thank you very much!

**Comment by AnKingMed** [comment]
I think it's reasonable to remove the image shrinking options

**Comment by abdnh** [comment]
> I think it's reasonable to remove the image shrinking options

Done.

I pushed the changes to the master branch. The old code that works on 2.1.40 is now in the [2.1.40](https://github.com/AnKing-VIP/Browser-Resizer/tree/2.1.40) branch. We need to create a new branch on AnkiWeb for 2.1.50+ and upload the latest master code there. Let me know once you test the changes and I'll upload it.

**Comment by AnKingMed** [comment]
@DoctorToBeIn23 can you test it?
@abdnh we should update this repo to match the other repos so that you can do the github action and create a new release

**Comment by abdnh** [comment]
>  @abdnh we should update this repo to match the other repos so that you can do the github action and create a new release

Done.

**Comment by AnKingMed** [comment]
Awesome thank you! @DoctorToBeIn23 will you test? @aPaci95 you're welcome to test as well. I just created a new 2.0 release

**Comment by DoctorToBeIn23** [comment]
Functions correctly!

**Comment by AnKingMed** [comment]
@abdnh if @DoctorToBeIn23 thinks its working, lets go ahead and push it to AnkiWeb

**Comment by abdnh** [comment]
> lets go ahead and push it to AnkiWeb

Done.

**Comment by AnKingMed** [comment]
Awesome! Is there any way to make it work better with the ReColor addon? I can make another issue for this if so

![image](https://github.com/AnKing-VIP/Browser-Resizer/assets/57678116/f334631e-9fd2-4335-8134-d7a510c64a04)

**Comment by AnKingMed** [comment]
Note the sidebar is dark and there is a dark line in between each field

**Comment by AnKingMed** [comment]
Also @abdnh it looks like the images we have on AnkiWeb aren't working if you have a sec to replace those (thank you!) 
![image](https://github.com/AnKing-VIP/Browser-Resizer/assets/57678116/c1001722-48ad-466f-a931-f92d1648899d)

**Comment by abdnh** [comment]
Image links updated.

> Note the sidebar is dark

This happens in dark mode also without ReColor. I'll look into it.

> there is a dark line in between each field

This appears to be something in ReColor as I can reproduce it without Browser Resizer.

**Comment by AnKingMed** [comment]
oh weird. Good to know. We should investigate that eventually then. Thanks for looking into this!
