### ISSUE TITLE
Won't install 23.10Qt6

### ISSUE THREAD

**Issue by DoctorToBeIn23** [AnKingMed/Browser-Resizer#12]

**Comment by abdnh** [comment]
The add-on is installing without errors for me on 23.10, but it seems it's no longer working (even in 2.1.66). I see there are open PRs (#3 #4 #7) from years ago so I assume this is not a new issue. @AnKingMed should I review the PRs and do any necessary changes to make it work? The add-on probably needs a full rewrite at this point.

**Comment by abdnh** [comment]
Just remembered I commented in #11 😅

**Comment by AnKingMed** [comment]
I think its reasonable to just rewrite at this point if you want. Could just make it a separate branch on here?

**Comment by abdnh** [comment]
See update: https://github.com/AnKing-VIP/Browser-Resizer/issues/11#issuecomment-1791771077

Closing this.
