### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Bakr-Ali** [AnKingMed/Browser-Resizer#5]
Hello AnKing!
After installing the addon for the first time and restarting Anki, Anki shows this error at start up:
```
An add-on you installed failed to load. If problems persist, please go to the Tools >Add-ons menu, and disable or delete the add-on.
When loading 'Browser Resizer':
Traceback (most recent call last):
File "aqt\addons.py", line 80, in loadAddons
File "C:\Users\[USER NAME]\AppData\Roaming\Anki2\addons21\1435775540\__init__.py", line 5, in <module>
from . import shrink_editor
C:\Users\[USER NAME]\AppData\Roaming\Anki2\addons21\1435775540\shrink_editor.py", line 26, in <module
from anki.utils import pointVersion
ImportError: cannot import name 'pointVersion'
```

Anki Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3

Windows 10

**Comment by AnKingMed** [comment]
Apologies for the late response to this. It looks like that feature was added around 2.1.22 so if you upgrade to that or beyond then it should work. I'll adjust it on AnkiWeb. I don't have time at the moment to go through my add-on and trim all the new features out for older versions, but you're welcome to do that if you'd like and the browser resizing portion of it should still work
