### ISSUE TITLE
2.1.45 Alpha 1 -> add-on broken (not sure if it is because of the 2.1.41+ update) (was using the version on anki add-on)

### ISSUE THREAD

**Issue by NamelessGO** [AnKingMed/Browser-Resizer#6]
![image](https://user-images.githubusercontent.com/66227691/118550344-90284600-b72a-11eb-8d69-4ddc269f1cf1.png)
https://www.reddit.com/r/Anki/comments/neoihx/anki_2145_alpha/ (changelogs)

**Comment by AnKingMed** [comment]
This and tons of other addons... I'll look into it as we move into betas
