### ISSUE TITLE
Hello, my friend.

### ISSUE THREAD

**Issue by Ad-apps** [AnKingMed/Browser-Resizer#8]
I  saw your Anki addon and I really want to start writing too. But I'm really confused on how to start doing so. I wonder if you could maybe give me some guidance? Thanks a lot. My discord is husband#7642 in case you're interested.

**Comment by AnKingMed** [comment]
I'm probably one of the worst people to help you write an add-on unfortunately. My software coding knowledge is very rudimentary. I'd recommend checking out the r/Anki reddit page and the discord linked there.
